version: "3.9"

services:
  palmmind_backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: palmmind_backend:v1
    container_name: palmmind_backend_system
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - /var/www/public-image:/var/www/app/palmmind/public-image
    restart: unless-stopped
    command: [ "node", "-r", "tsconfig-paths/register", "build/index.js" ]
