import {EnvironmentLabelInterface} from "@interface/env.interface";

const environmentVariable: EnvironmentLabelInterface = {
    ACCESS_TOKEN_SECRET: "ACCESS_TOKEN_SECRET",
    REFRESH_TOKEN_SECRET: "REFRESH_TOKEN_SECRET",
    REFRESH_TOKEN_EXPIRY_DAY: 'REFRESH_TOKEN_EXPIRY_DAY',
    ACCESS_TOKEN_EXPIRY_HOUR: 'ACCESS_TOKEN_EXPIRY_HOUR',

    PORT: "PORT",
    NODE_ENV: "NODE_ENV",
    CIPHER_SECRET_KEY: "CIPHER_SECRET_KEY",
    SEED_ADMIN_EMAIL: 'SEED_ADMIN_EMAIL',
    SEED_ADMIN_PASSWORD: 'SEED_ADMIN_PASSWORD',

    EMAIL_SMTP_HOST: 'EMAIL_SMTP_HOST',
    EMAIL_PASSWORD: 'EMAIL_PASSWORD',
    EMAIL_SMTP_PORT: 'EMAIL_SMTP_PORT',
    EMAIL_AUTH_ID: 'EMAIL_AUTH_ID',

    MONGODB_HOST: 'MONGODB_HOST',
    MONGODB_DB: 'MONGODB_DB',
    MONGODB_PARAMS: 'MONGODB_PARAMS',

    REDIS_HOST: 'REDIS_HOST',
    REDIS_PORT: 'REDIS_PORT',
    REDIS_USERNAME: 'REDIS_USERNAME',
    REDIS_PASSWORD: 'REDIS_PASSWORD',
    API_GATEWAY_HOST: 'API_GATEWAY_HOST',
    FRONTEND_HOST: 'FRONTEND_HOST',
};
export default environmentVariable;
