# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Production CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ "production" ]

jobs:
  build:
    runs-on: [ 'self-hosted', 'production-runner' ]
    strategy:
      matrix:
        node-version: [ 20.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - run: |
          touch .env
          echo "${{ secrets.ENV_FILE_PRODUCTION }}" > .env
      - run: make github_actions
      # Cleanup Docker images and containers
      - name: Cleanup Docker Images
        run: |
          docker system prune -af || true
